### ISSUE TITLE
Louis CK gif

### ISSUE THREAD

**Issue by logemerson** [learn-co-curriculum/js-ajax-advanced-ajax-lab#1]
I realize this isn't exactly erroneous, but given recent events, replacing the gif on line 20 of README.md would improve the lab for some.

For ease of replacement, here are some suggestions:

- https://media.giphy.com/media/vgUFOWBwBkziE/giphy.gif (alt="stanley")

- https://media.giphy.com/media/JqSd3zNscEIeI/giphy.gif (alt="prince")

- https://media.giphy.com/media/10Jpr9KSaXLchW/giphy.gif (alt="jack nicholson")

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We corrected the readme.

As always thank you for contributing!
