### ISSUE TITLE
"XHR request" is redundant

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/js-ajax-advanced-ajax-lab#2]
Finding language in this section particularly key. May make sense to clarify that XHR = XMLHttpRequest, and to not use "XHR request" because it is confusing.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @d-d-d-dalia .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
