### ISSUE TITLE
Code not working on my end how it's presented...

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/js-ajax-advanced-ajax-lab#4]
From the readme:

`<script id="repository-template" type="text/x-handlebars-template">
  <ul>
   {{#each this}}
     <li>
       <h2><a href="{{html_url}}">{{name}}</a></h2>
       {{> authorPartial owner }}
       <p>Watchers: {{watchers_count}}</p>
       <p>Forks: {{forks_count}}</p>
       <p>Issues: {{open_issues_count}}</p>
     </li>
    {{/each}}
  </ul>
</script>
<script id="author-partial-template" type="text/x-handlebars-template">
  <section>
    <header><h4>Created By {{login}}</h4></header>
    <img src="{{avatar_url}}" height="32" width="32">
  </section>
</script>`

> We created a new script tag for our partial template, and we're rendering it within our repository template via the {{> authorPartial owner}} line. _**We're passing owner to the template, which is really this.owner, or the owner property of the current repository object since we are inside the {{#each}} block.**_

So on my end, passing "owner" to the partial doesn't display any data when it's used on the partial:

`    <script id="author-partial-template" type="text/x-handlebars-template">
      <section>
        <header><h4>Created By {{owner.login}}</h4></header>
        <img src="{{owner.avatar_url}}" height="32" width="32">
      </section>
    </script>`

But when I changed "owner" for "this", everything works just fine. And as I remember from a previous lesson, we where passing the object itself to the partial by passing "this".

So the way I have it on my end, that ended up working, is like this:

`    <script id="repository-template" type="text/x-handlebars-template">
      <ul>
       {{#each this}}
         <li>
           <h2><a href="{{html_url}}">{{name}}</a></h2>
           {{> authorPartial this}}
           <p>Watchers: {{watchers_count}}</p>
           <p>Forks: {{forks_count}}</p>
           <p>Issues: {{open_issues_count}}</p>
         </li>
        {{/each}}
      </ul>
    </script>
    <script id="author-partial-template" type="text/x-handlebars-template">
      <section>
        <header><h4>Created By {{owner.login}}</h4></header>
        <img src="{{owner.avatar_url}}" height="32" width="32">
      </section>
    </script>`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Ary770.

We are in the process of updating the materials in this section and will update this lesson referencing the issues that have been opened.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
