### ISSUE TITLE
"Handlebar Templatess" sub header has two s's

### ISSUE THREAD

**Issue by srolandmarshall** [learn-co-curriculum/js-ajax-advanced-ajax-lab#5]
"Handlebar Templatess" sub header has two s's

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @srolandmarshall.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
