### ISSUE TITLE
Should be called a code-along lesson, not a lab.

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-ajax-advanced-ajax-lab#6]
Also -- it would be helpful to have the complete solution code, so if something goes wrong in the code-along, it's easier to see where the bug is; especially in a learning context. Thanks!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MiriamPeskowitz.

We are in the process of updating the materials in this section and will update this lesson referencing the issues that have been opened.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
